name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        expo-version: ["^48.0.0"]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Expo CLI
        run: npm install -g expo-cli
      - name: Install dependencies
        run: npm ci
      - name: Run linter
        run: npx eslint src/**
      - name: Run tests
        run: npm test
